- alias: 'Run off living room roku when TV turns off'
  trigger:
    - platform: state
      entity_id: media_player.vizio_smartcast
      to: 'off'
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.living_room
        source: Home
    - service: media_player.turn_off
      data:
        entity_id: media_player.vizio_smartcast
- alias: 'Turn off computer when idle'
  trigger:
    - platform: state
      entity_id: sensor.desktop_ssh_connections
      to: '0'
    - platform: state
      entity_id: sensor.plex_godmachine
      to: '0'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.desktop_ssh_connections
        state: '0'
      - condition: state
        entity_id: sensor.desktop_active
        state: '0'
      - condition: state
        entity_id: sensor.plex_godmachine
        state: '0'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.sabnzbd_status
            state: 'Idle'
          - condition: state
            entity_id: sensor.sabnzbd_status
            state: 'Paused'
  action:
    - delay:
        minutes: 10
    - condition: and
      conditions:
        - condition: state
          entity_id: sensor.desktop_ssh_connections
          state: '0'
        - condition: state
          entity_id: sensor.desktop_active
          state: '0'
        - condition: state
          entity_id: sensor.plex_godmachine
          state: '0'
    - service: switch.turn_off
      data:
        entity_id:
          - switch.desktop
- alias: Connie or Trey is home
  trigger:
    - platform: state
      entity_id: person.connie
      to: 'home'
    - platform: state
      entity_id: person.trey
      to: 'home'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
      - condition: sun
        before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.downstairs_entry
    - delay:
        minutes: 5
    - service: light.turn_off
      data:
        entity_id:
          - light.downstairs_entry
- alias: Trey is home
  trigger:
    - platform: state
      entity_id: person.trey
      to: 'home'
  action:
    - service: script.announce_trey_is_home
- alias: Connie is home
  trigger:
    - platform: state
      entity_id: person.connie
      to: 'home'
  action:
    - service: script.announce_connie_is_home
- alias: Turn on living room lights if no one home
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states("person.trey") != "home" }}'
      - condition: template
        value_template: '{{ states("person.connie") != "home" }}'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.living_room_lights
