- alias: 'Turn on compute'
  trigger:
    - platform: state
      entity_id: binary_sensor.desktop_ping
      to: 'on'
  action:
    - service: script.restart_ha
- alias: 'Turn off computer when idle'
  trigger:
    - platform: state
      entity_id: sensor.desktop_ssh_connections
      to: '0'
    - platform: state
      entity_id: sensor.plex_godmachine
      to: '0'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.desktop_ssh_connections
        state: '0'
      - condition: state
        entity_id: sensor.desktop_active
        state: '0'
      - condition: state
        entity_id: sensor.plex_godmachine
        state: '0'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.sabnzbd_status
            state: 'Idle'
          - condition: state
            entity_id: sensor.sabnzbd_status
            state: 'Paused'
  action:
    - delay:
        minutes: 10
    - condition: and
      conditions:
        - condition: state
          entity_id: sensor.desktop_ssh_connections
          state: '0'
        - condition: state
          entity_id: sensor.desktop_active
          state: '0'
        - condition: state
          entity_id: sensor.plex_godmachine
          state: '0'
    - service: switch.turn_off
      data:
        entity_id:
          - switch.desktop
