name: Test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Setup secrets
        run: mv .github/config/secrets.yaml secrets.yaml
      - name: Setup custom components
        run: |
          mkdir custom_components
          wget -O /tmp/hacs.zip "https://github.com/hacs/integration/releases/latest/download/hacs.zip"
          unzip /tmp/hacs.zip -d custom_components/hacs
          git clone https://github.com/albertogeniola/meross-homeassistant.git /tmp/meross-homeassistant
          cp -r /tmp/meross-homeassistant/custom_components/meross_cloud custom_components/meross_cloud
          wget -O /tmp/alexa_media.zip https://github.com/custom-components/alexa_media_player/releases/latest/download/alexa_media.zip
          unzip /tmp/alexa_media.zip -d custom_components/alexa_media
      - name: Run tests
        run: make test
